name: brick_breaker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0-296.3.beta

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.15.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
